apiVersion: v1
kind: PersistentVolumeClaim
metedata:
  name: fileserver-httpd
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: fileserver-httpd
  resources:
    requests:
      storage: 500Gi